apiVersion: v1
kind: pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: debug
spec:
  containers:
    - name: debug
      image: ruthvikk1214/debug:1.0
      command: ["sleep", "3600"]