apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: shipping
    tier: backend
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: shipping
    tier: backend
spec: 
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      env: dev
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: shipping
        tier: backend
    spec:
      containers:
        - name: shipping
          image: ruthvikk1214/shipping:1.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: shipping
    tier: backend
spec: 
  selector:
    project: roboshop
    env: dev
    component: shipping
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      name: shipping