apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: ruthvikk1214/mysql:1.0
          ports:
            - containerPort: 27017
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mysql
    tier: db
spec:
  selector:
    project: roboshop
    env: dev
    component: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql