apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
spec: 
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      env: dev
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: catalogue
        tier: backend
    spec:
      containers:
        - name: catalogue
          image: ruthvikk1214/catalogue:1.0
          envFrom:
            - configMapRef:
                name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
spec: 
  selector:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      name: catalogue
